apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-deployment
  namespace: fe-ns
  labels:
    app: fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fe
  template:
    metadata:
      labels:
        app: fe
    spec:
      containers:
      - name: profile-fe
        image: mohamed010/frontend-profile
        ports:
        - containerPort: 80
      tolerations:
      - key: "fe-worker"
        operator: "Equal"
        value: "fe-worker"
        effect: "NoSchedule"